// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gprpc.proto
package com.github.wuchunhuan.gprpc_java.protocol;
public final class Gprpc {
  private Gprpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface rpc_dataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc_data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.rpc_data.type data_type = 1;</code>
     */
    int getDataTypeValue();
    /**
     * <code>.rpc_data.type data_type = 1;</code>
     */
    Gprpc.rpc_data.type getDataType();

    /**
     * <code>string svc_name = 2;</code>
     */
    java.lang.String getSvcName();
    /**
     * <code>string svc_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getSvcNameBytes();

    /**
     * <code>string method_name = 3;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>string method_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>uint32 call_id = 4;</code>
     */
    int getCallId();

    /**
     * <code>bool compress = 5;</code>
     */
    boolean getCompress();

    /**
     * <code>bool encrypt = 6;</code>
     */
    boolean getEncrypt();

    /**
     * <code>bool failed = 7;</code>
     */
    boolean getFailed();

    /**
     * <code>int32 error_code = 8;</code>
     */
    int getErrorCode();

    /**
     * <pre>
     *cli ip
     *srv ip
     * </pre>
     *
     * <code>string reason = 9;</code>
     */
    java.lang.String getReason();
    /**
     * <pre>
     *cli ip
     *srv ip
     * </pre>
     *
     * <code>string reason = 9;</code>
     */
    com.google.protobuf.ByteString
        getReasonBytes();

    /**
     * <code>bytes content = 10;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code rpc_data}
   */
  public  static final class rpc_data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rpc_data)
      rpc_dataOrBuilder {
    // Use rpc_data.newBuilder() to construct.
    private rpc_data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private rpc_data() {
      dataType_ = 0;
      svcName_ = "";
      methodName_ = "";
      callId_ = 0;
      compress_ = false;
      encrypt_ = false;
      failed_ = false;
      errorCode_ = 0;
      reason_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private rpc_data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              svcName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 32: {

              callId_ = input.readUInt32();
              break;
            }
            case 40: {

              compress_ = input.readBool();
              break;
            }
            case 48: {

              encrypt_ = input.readBool();
              break;
            }
            case 56: {

              failed_ = input.readBool();
              break;
            }
            case 64: {

              errorCode_ = input.readInt32();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              reason_ = s;
              break;
            }
            case 82: {

              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Gprpc.internal_static_rpc_data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Gprpc.internal_static_rpc_data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Gprpc.rpc_data.class, Gprpc.rpc_data.Builder.class);
    }

    /**
     * Protobuf enum {@code rpc_data.type}
     */
    public enum type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REQUEST = 0;</code>
       */
      REQUEST(0),
      /**
       * <code>RESPONSE = 1;</code>
       */
      RESPONSE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>REQUEST = 0;</code>
       */
      public static final int REQUEST_VALUE = 0;
      /**
       * <code>RESPONSE = 1;</code>
       */
      public static final int RESPONSE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static type valueOf(int value) {
        return forNumber(value);
      }

      public static type forNumber(int value) {
        switch (value) {
          case 0: return REQUEST;
          case 1: return RESPONSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<type>() {
              public type findValueByNumber(int number) {
                return type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Gprpc.rpc_data.getDescriptor().getEnumTypes().get(0);
      }

      private static final type[] VALUES = values();

      public static type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:rpc_data.type)
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>.rpc_data.type data_type = 1;</code>
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.rpc_data.type data_type = 1;</code>
     */
    public Gprpc.rpc_data.type getDataType() {
      Gprpc.rpc_data.type result = Gprpc.rpc_data.type.valueOf(dataType_);
      return result == null ? Gprpc.rpc_data.type.UNRECOGNIZED : result;
    }

    public static final int SVC_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object svcName_;
    /**
     * <code>string svc_name = 2;</code>
     */
    public java.lang.String getSvcName() {
      java.lang.Object ref = svcName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        svcName_ = s;
        return s;
      }
    }
    /**
     * <code>string svc_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSvcNameBytes() {
      java.lang.Object ref = svcName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        svcName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object methodName_;
    /**
     * <code>string method_name = 3;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string method_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CALL_ID_FIELD_NUMBER = 4;
    private int callId_;
    /**
     * <code>uint32 call_id = 4;</code>
     */
    public int getCallId() {
      return callId_;
    }

    public static final int COMPRESS_FIELD_NUMBER = 5;
    private boolean compress_;
    /**
     * <code>bool compress = 5;</code>
     */
    public boolean getCompress() {
      return compress_;
    }

    public static final int ENCRYPT_FIELD_NUMBER = 6;
    private boolean encrypt_;
    /**
     * <code>bool encrypt = 6;</code>
     */
    public boolean getEncrypt() {
      return encrypt_;
    }

    public static final int FAILED_FIELD_NUMBER = 7;
    private boolean failed_;
    /**
     * <code>bool failed = 7;</code>
     */
    public boolean getFailed() {
      return failed_;
    }

    public static final int ERROR_CODE_FIELD_NUMBER = 8;
    private int errorCode_;
    /**
     * <code>int32 error_code = 8;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int REASON_FIELD_NUMBER = 9;
    private volatile java.lang.Object reason_;
    /**
     * <pre>
     *cli ip
     *srv ip
     * </pre>
     *
     * <code>string reason = 9;</code>
     */
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reason_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *cli ip
     *srv ip
     * </pre>
     *
     * <code>string reason = 9;</code>
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 10;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != Gprpc.rpc_data.type.REQUEST.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (!getSvcNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, svcName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, methodName_);
      }
      if (callId_ != 0) {
        output.writeUInt32(4, callId_);
      }
      if (compress_ != false) {
        output.writeBool(5, compress_);
      }
      if (encrypt_ != false) {
        output.writeBool(6, encrypt_);
      }
      if (failed_ != false) {
        output.writeBool(7, failed_);
      }
      if (errorCode_ != 0) {
        output.writeInt32(8, errorCode_);
      }
      if (!getReasonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, reason_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(10, content_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != Gprpc.rpc_data.type.REQUEST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (!getSvcNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, svcName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, methodName_);
      }
      if (callId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, callId_);
      }
      if (compress_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, compress_);
      }
      if (encrypt_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, encrypt_);
      }
      if (failed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, failed_);
      }
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, errorCode_);
      }
      if (!getReasonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, reason_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, content_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Gprpc.rpc_data)) {
        return super.equals(obj);
      }
      Gprpc.rpc_data other = (Gprpc.rpc_data) obj;

      boolean result = true;
      result = result && dataType_ == other.dataType_;
      result = result && getSvcName()
          .equals(other.getSvcName());
      result = result && getMethodName()
          .equals(other.getMethodName());
      result = result && (getCallId()
          == other.getCallId());
      result = result && (getCompress()
          == other.getCompress());
      result = result && (getEncrypt()
          == other.getEncrypt());
      result = result && (getFailed()
          == other.getFailed());
      result = result && (getErrorCode()
          == other.getErrorCode());
      result = result && getReason()
          .equals(other.getReason());
      result = result && getContent()
          .equals(other.getContent());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      hash = (37 * hash) + SVC_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSvcName().hashCode();
      hash = (37 * hash) + METHOD_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      hash = (37 * hash) + CALL_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCallId();
      hash = (37 * hash) + COMPRESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCompress());
      hash = (37 * hash) + ENCRYPT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEncrypt());
      hash = (37 * hash) + FAILED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFailed());
      hash = (37 * hash) + ERROR_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + getReason().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Gprpc.rpc_data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Gprpc.rpc_data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Gprpc.rpc_data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Gprpc.rpc_data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Gprpc.rpc_data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Gprpc.rpc_data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Gprpc.rpc_data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Gprpc.rpc_data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Gprpc.rpc_data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Gprpc.rpc_data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Gprpc.rpc_data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Gprpc.rpc_data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Gprpc.rpc_data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rpc_data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc_data)
        Gprpc.rpc_dataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Gprpc.internal_static_rpc_data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Gprpc.internal_static_rpc_data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Gprpc.rpc_data.class, Gprpc.rpc_data.Builder.class);
      }

      // Construct using Gprpc.rpc_data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        svcName_ = "";

        methodName_ = "";

        callId_ = 0;

        compress_ = false;

        encrypt_ = false;

        failed_ = false;

        errorCode_ = 0;

        reason_ = "";

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Gprpc.internal_static_rpc_data_descriptor;
      }

      public Gprpc.rpc_data getDefaultInstanceForType() {
        return Gprpc.rpc_data.getDefaultInstance();
      }

      public Gprpc.rpc_data build() {
        Gprpc.rpc_data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Gprpc.rpc_data buildPartial() {
        Gprpc.rpc_data result = new Gprpc.rpc_data(this);
        result.dataType_ = dataType_;
        result.svcName_ = svcName_;
        result.methodName_ = methodName_;
        result.callId_ = callId_;
        result.compress_ = compress_;
        result.encrypt_ = encrypt_;
        result.failed_ = failed_;
        result.errorCode_ = errorCode_;
        result.reason_ = reason_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Gprpc.rpc_data) {
          return mergeFrom((Gprpc.rpc_data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Gprpc.rpc_data other) {
        if (other == Gprpc.rpc_data.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        if (!other.getSvcName().isEmpty()) {
          svcName_ = other.svcName_;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.getCallId() != 0) {
          setCallId(other.getCallId());
        }
        if (other.getCompress() != false) {
          setCompress(other.getCompress());
        }
        if (other.getEncrypt() != false) {
          setEncrypt(other.getEncrypt());
        }
        if (other.getFailed() != false) {
          setFailed(other.getFailed());
        }
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        if (!other.getReason().isEmpty()) {
          reason_ = other.reason_;
          onChanged();
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Gprpc.rpc_data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Gprpc.rpc_data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int dataType_ = 0;
      /**
       * <code>.rpc_data.type data_type = 1;</code>
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <code>.rpc_data.type data_type = 1;</code>
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.rpc_data.type data_type = 1;</code>
       */
      public Gprpc.rpc_data.type getDataType() {
        Gprpc.rpc_data.type result = Gprpc.rpc_data.type.valueOf(dataType_);
        return result == null ? Gprpc.rpc_data.type.UNRECOGNIZED : result;
      }
      /**
       * <code>.rpc_data.type data_type = 1;</code>
       */
      public Builder setDataType(Gprpc.rpc_data.type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.rpc_data.type data_type = 1;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object svcName_ = "";
      /**
       * <code>string svc_name = 2;</code>
       */
      public java.lang.String getSvcName() {
        java.lang.Object ref = svcName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          svcName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string svc_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSvcNameBytes() {
        java.lang.Object ref = svcName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          svcName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string svc_name = 2;</code>
       */
      public Builder setSvcName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        svcName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string svc_name = 2;</code>
       */
      public Builder clearSvcName() {
        
        svcName_ = getDefaultInstance().getSvcName();
        onChanged();
        return this;
      }
      /**
       * <code>string svc_name = 2;</code>
       */
      public Builder setSvcNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        svcName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>string method_name = 3;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string method_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method_name = 3;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method_name = 3;</code>
       */
      public Builder clearMethodName() {
        
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>string method_name = 3;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        methodName_ = value;
        onChanged();
        return this;
      }

      private int callId_ ;
      /**
       * <code>uint32 call_id = 4;</code>
       */
      public int getCallId() {
        return callId_;
      }
      /**
       * <code>uint32 call_id = 4;</code>
       */
      public Builder setCallId(int value) {
        
        callId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 call_id = 4;</code>
       */
      public Builder clearCallId() {
        
        callId_ = 0;
        onChanged();
        return this;
      }

      private boolean compress_ ;
      /**
       * <code>bool compress = 5;</code>
       */
      public boolean getCompress() {
        return compress_;
      }
      /**
       * <code>bool compress = 5;</code>
       */
      public Builder setCompress(boolean value) {
        
        compress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool compress = 5;</code>
       */
      public Builder clearCompress() {
        
        compress_ = false;
        onChanged();
        return this;
      }

      private boolean encrypt_ ;
      /**
       * <code>bool encrypt = 6;</code>
       */
      public boolean getEncrypt() {
        return encrypt_;
      }
      /**
       * <code>bool encrypt = 6;</code>
       */
      public Builder setEncrypt(boolean value) {
        
        encrypt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool encrypt = 6;</code>
       */
      public Builder clearEncrypt() {
        
        encrypt_ = false;
        onChanged();
        return this;
      }

      private boolean failed_ ;
      /**
       * <code>bool failed = 7;</code>
       */
      public boolean getFailed() {
        return failed_;
      }
      /**
       * <code>bool failed = 7;</code>
       */
      public Builder setFailed(boolean value) {
        
        failed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool failed = 7;</code>
       */
      public Builder clearFailed() {
        
        failed_ = false;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>int32 error_code = 8;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>int32 error_code = 8;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 error_code = 8;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object reason_ = "";
      /**
       * <pre>
       *cli ip
       *srv ip
       * </pre>
       *
       * <code>string reason = 9;</code>
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *cli ip
       *srv ip
       * </pre>
       *
       * <code>string reason = 9;</code>
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *cli ip
       *srv ip
       * </pre>
       *
       * <code>string reason = 9;</code>
       */
      public Builder setReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *cli ip
       *srv ip
       * </pre>
       *
       * <code>string reason = 9;</code>
       */
      public Builder clearReason() {
        
        reason_ = getDefaultInstance().getReason();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *cli ip
       *srv ip
       * </pre>
       *
       * <code>string reason = 9;</code>
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reason_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 10;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 10;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 10;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:rpc_data)
    }

    // @@protoc_insertion_point(class_scope:rpc_data)
    private static final Gprpc.rpc_data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Gprpc.rpc_data();
    }

    public static Gprpc.rpc_data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<rpc_data>
        PARSER = new com.google.protobuf.AbstractParser<rpc_data>() {
      public rpc_data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new rpc_data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<rpc_data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<rpc_data> getParserForType() {
      return PARSER;
    }

    public Gprpc.rpc_data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013gprpc.proto\"\360\001\n\010rpc_data\022!\n\tdata_type\030" +
      "\001 \001(\0162\016.rpc_data.type\022\020\n\010svc_name\030\002 \001(\t\022" +
      "\023\n\013method_name\030\003 \001(\t\022\017\n\007call_id\030\004 \001(\r\022\020\n" +
      "\010compress\030\005 \001(\010\022\017\n\007encrypt\030\006 \001(\010\022\016\n\006fail" +
      "ed\030\007 \001(\010\022\022\n\nerror_code\030\010 \001(\005\022\016\n\006reason\030\t" +
      " \001(\t\022\017\n\007content\030\n \001(\014\"!\n\004type\022\013\n\007REQUEST" +
      "\020\000\022\014\n\010RESPONSE\020\001B\003\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_rpc_data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_data_descriptor,
        new java.lang.String[] { "DataType", "SvcName", "MethodName", "CallId", "Compress", "Encrypt", "Failed", "ErrorCode", "Reason", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
